### ISSUE TITLE
Working with lick detection solution for VR foraging task

### ISSUE THREAD

**Issue by cindypoo** [AllenNeuralDynamics/Aind.Behavior.VrForaging#158]
Grounding issue? 
Headplate needs to be in better contact with skull during surgery? 
Mouse size issue? (can be changed with threshold tuning)

**Comment by cindypoo** [comment]
@Poofjunior 
Licks not reliably detected. 
Drift over time (eg. .when tube is more or less dry)

Discussed: relax 1ms requirement to 10ms requirement

**Comment by Poofjunior** [comment]
@tiffanyona I fixed the starting threshold values, which should be a huge quality-of-life improvement when we tune these values for debugging. Let's schedule some time to reflash the lick detectors you have.

**Comment by tiffanyona** [comment]
@Poofjunior Today after 3.30 the setup and I are free! Can we make it then? Hopefully this update can fix the main issues!

**Comment by cindypoo** [comment]
[like]  Cindy Poo reacted to your message:
________________________________

**Comment by tiffanyona** [comment]
Reflashing with quality of life improvement in the triggers and test on Friday with raw data online (aside of behavioral training)

**Comment by tiffanyona** [comment]
Sonya acquired raw data to have a better look at it. 

Today 2/12 there were still a lot of issues with the detection, specially in red boxes. Things still pending to do to try to upgrade the signal: 
- [ ] Increase the the time requirement to 10ms instead of 1ms. 
- [ ] Ground the lights in the red boxes.

**Comment by cindypoo** [comment]
I talked to Sonya today. I propose we revert back to Janelia lick boards for all behavioral rigs for now. 

We prob will have to re-visit the idea of having the same board solution for both ephys and behavioral rigs. Might make more sense to fork it. 

For now, reverting back to Janelia boards will allow us to train mice without adding timeline pressure on Sonya's project, and without delaying training plans.
