### ISSUE TITLE
I/O crash in both computers. 

### ISSUE THREAD

**Issue by tiffanyona** [AllenNeuralDynamics/Aind.Behavior.VrForaging#160]
The sessions that were affected were: 
690167/20231207113815
699894/20231207113459

This happened in the medium red system. After 50minutes of training aprox, both computers crashed at the same time. An error message flashed saying "I/O... something something" and quickly closed without manipulation. In MR2 the whole bonsai closed. In MR1 only stopped the workflow but it didn't close bonsai. 

There was enough space in both computers. The likely culprit is a grounding loop issue or something power supply related.

**Comment by tiffanyona** [comment]
MR1 has started to show this issue again really often. The only thing that is somehow linked to ir is whenever the tower istself is touch so maybe there is an unstable connection somewhere.

**Comment by bruno-f-cruz** [comment]
> Again both computers crashed simultaneously, bonsai didn't close this time in either of them. Both of them had the same error message, but in one the node of the Licksensor was in red and in the other the one of the Olfactometer. Maybe it is important to note, but this happened again on the red system, hasn't occurred in the white yet and the share everything, even the fact that one box has the licksensor and the other one hasn't.

Is the current error the same as this one? Again, this looks like a communication problem with the Harp Devices.

**Comment by travisjramirez** [comment]
2/27 
ID 899: I/O error, MR1 hardware issue,

2/26
ID 899: I/O error, MR1- before Travis put mouse ion, Bruno came up and looked, HARP Olfactometer crash
ID 165: I/O error, MR1- before Olivia put mouse in

2/12
ID 899: possible I/O error when loading mice in MR1- Travis

2/1
ID 899: possible I/O error when loading mice in MR1, crashed when door opens -Olivia

**Comment by bruno-f-cruz** [comment]
3/6:

Mr1- head clamp -> i/o error before 5 seconds of closing door.

Mr1- inconsistent licks

W4- no lick detection on graph

Mr2- i/o error when opening door to put mouse in. After restarting bonsai, saw a com7 error.

Mr1- launched bonsai twice and visualizer did not show.( spoke to Tiffany and it was fixed)
7 i/o errors in total during mouse 690165 session.

2 of the I / 0 error happened when opening the rig door to put the mouse in then closing the door.

5 of the I/0 error happened when mouse 690165 was doing the task. I closed out of bonsai and relaunched 5 times on the 6th crash i restarted the computer and launched bonsai… it crashed again when mouse was doing task.

**Comment by travisjramirez** [comment]
3/5 (morning session):
MR1 I/O error (morning -during session ) at 19:53 - Harp Devices node

**Comment by cindypoo** [comment]
@Poofjunior will go through electrical wiring diagram of current rigs. 
Related to MPE ticket here http://mpe-redirects/MPETracking/ItemID=3306

**Comment by Oliviau36** [comment]
3/11-3/13 crashes

Mr1  I/0 error happened in 2mins of mouse 690165 during tasks.

 Mr1 I/0 error (morning) harp devices

W2 com3 error and device attached to the system is not functioning error when door is closed

W4 lick spout not detecting licks 

Mr1 I/0 error happened before session three times. (harp device)

MR2- licking inconsistent morning

Mr1-I/0 error happened while fixing lick spout. door was open when bonsai crashed twice

**Comment by bruno-f-cruz** [comment]
I am closing this (for the 5th time? haha). As usual, re-open if it pops up again. *knocks on wood*
