### ISSUE TITLE
Schema without updaaters doesn;t work properly

### ISSUE THREAD

**Issue by tiffanyona** [AllenNeuralDynamics/Aind.Behavior.VrForaging#201]
[example_vr_task_logic_noupdaters.json](https://github.com/AllenNeuralDynamics/Aind.Behavior.VrForaging/files/14074595/example_vr_task_logic_noupdaters.json)

Launches the task but stops detecting stops after the first harvested site.

**Comment by bruno-f-cruz** [comment]
fixed via 2f9c8a036b1ac2c94a7fb788da6fa95c5e2e5fc2
