### ISSUE TITLE
Release `0.1.1` deployment issues

### ISSUE THREAD

**Issue by tiffanyona** [AllenNeuralDynamics/Aind.Behavior.VrForaging#202]
Issues observed when testing the PR:

- Odor valves don't open (no red light when there should be on the olfactometer). Raw data looks like there is only one READ command and no WRITEs even though there are several EndValve triggers.
- Patch identity and Site-Intersite-Interpatch plots are not working in the main visualizer.
- Change default water given by ForceReward to 3.

**Comment by tiffanyona** [comment]
- Water calibration seems to not be reversed yet. When I changed the fit so it looks like the calibration (opening times bottom and values recovered/iteration number), the valves opens too much in the task. 

For instance: 
Before I inputted :
Slope: 0.02
Intercept: -0.02
![image](https://github.com/AllenNeuralDynamics/Aind.Behavior.VrForaging/assets/33984148/9d620343-4613-46dd-98c5-2c6ad7d94ad9)

Now I input: 
Slope: 43.05
Intercept: 1.22
![image](https://github.com/AllenNeuralDynamics/Aind.Behavior.VrForaging/assets/33984148/d8c1c4a3-5aa9-420c-9376-72748d33a975)

**Comment by bruno-f-cruz** [comment]
Re: Water. This is what is currently going on in Bonsai

`delay(s) = water(a.u.) * CalibrationSlope + CalibrationIntercept`

I will change it to:
`delay(s) = (water - offset) / slope` so you can use the values from WR2.
I must have gotten confused when changing the model, sorry!

**Comment by bruno-f-cruz** [comment]
These should have all been fixed via 5be7aba3bb9a64f52f64aeb0ba5885e3c3ac5e8d
