### ISSUE TITLE
Order IR band pass filters for cameras

### ISSUE THREAD

**Issue by bruno-f-cruz** [AllenNeuralDynamics/Aind.Behavior.VrForaging#214]
https://opticalfiltershop.com/shop/specialty-filters/lidar/near-infrared-bandpass-filter-850nm-fwhm-100nm/

**Comment by bruno-f-cruz** [comment]
@tiffanyona what is the model we are using? Do you have a reference for the mechanical specs of the camera?

**Comment by bruno-f-cruz** [comment]
Looks like a 14x14mm square might do the trick.

**Comment by tiffanyona** [comment]
- On this line, make sure we have enough lenses and order more if necessary.
