### ISSUE TITLE
Integrate break and torque sensor of wheel in the task logic

### ISSUE THREAD

**Issue by bruno-f-cruz** [AllenNeuralDynamics/Aind.Behavior.VrForaging#217]

**Comment by cindypoo** [comment]
Need to define what manipulation is needed for torque control. 
- segmented by sites/intersite
- specified by distribution

**Comment by bruno-f-cruz** [comment]
Build a MVP around using the torque in the inter-patch-interval

**Comment by bruno-f-cruz** [comment]
Dependent on #251
