### ISSUE TITLE
Upgrade in visualizers to be compatible with new hardware

### ISSUE THREAD

**Issue by tiffanyona** [AllenNeuralDynamics/Aind.Behavior.VrForaging#223]
- [x] Harp sniff board to be displayed in the visualize instead of the analog signal from the Harp behavior. 
- [x] New camera display: 
   - [x]  Side camera: FLIR camera (optional). 
   - [x]  Face camera: FLIR camera (obligatory)
   - [x]  Top camera: USB camera (optional)

Two general questions about camera control:
- Is there a way to toggle whether the camera should save the data or not?
- Is there a way to select which camera is going to be displayed in the visualizer instead of having it preset?

**Comment by bruno-f-cruz** [comment]
Fixed via [5534050](https://github.com/AllenNeuralDynamics/Aind.Behavior.VrForaging/pull/219/commits/553405088a501b5f5d86006383f7b83816cd3a0b)
