### ISSUE TITLE
Add analog input from behavior in visualizer

### ISSUE THREAD

**Issue by tiffanyona** [AllenNeuralDynamics/Aind.Behavior.VrForaging#230]
Revert the plotting of the sniff sensor to show data coming from the Analog of the Behavior board.

**Comment by bruno-f-cruz** [comment]
Fixed via [9ee4aa8](https://github.com/AllenNeuralDynamics/Aind.Behavior.VrForaging/commit/9ee4aa87b0050f4f6fae4cb6336ec3264198dced)
