### ISSUE TITLE
`Register__StopCameras.bin` sends two stop messages when session ended.

### ISSUE THREAD

**Issue by NgD-Huy** [AllenNeuralDynamics/Aind.Behavior.VrForaging#244]
Per Bruno's request,

### **Session [716458\20240422T091200]**
When verifying that camera metadata.csv matched that of harp data for session   (ie., *SideBodyCamera\Metadata.csv* and *Register__Camera1Frame.bin*), I noticed that *Register__StopCameras.bin* sent two stop messages when the session ended. 

![image](https://github.com/AllenNeuralDynamics/Aind.Behavior.VrForaging/assets/159174908/8b5b248a-b85a-4458-8d75-d84ea84be5ba)

**Comparing the CSV file and the bin file of the full session**
Since the timestamps match 1:1, the (blue and green) lines overlap perfectly.
![image](https://github.com/AllenNeuralDynamics/Aind.Behavior.VrForaging/assets/159174908/c77d08c2-9ac9-4f4d-aafa-7cb2d3416794)

**Zoomed-in view to better show Register__StartCameras.bin and  Register__StopCameras.bin**
The difference between two stop signals is a 1000th of a millisecond so the difference cannot be seen on the chart.
![image](https://github.com/AllenNeuralDynamics/Aind.Behavior.VrForaging/assets/159174908/d0a6bf33-a619-44e4-b1e0-110e81a2addb)

**Comment by bruno-f-cruz** [comment]
Can you also add the data of the CamTrigger dataframe including the first 10 and last 10 frames? thanks!

**Comment by NgD-Huy** [comment]
> Can you also add the data of the CamTrigger dataframe including the first 10 and last 10 frames? thanks!

#### **Register__Camera1Frame.bin**
![Code_5PthUyER0O](https://github.com/AllenNeuralDynamics/Aind.Behavior.VrForaging/assets/159174908/dcc0257c-b71e-4d45-b73c-6da38e90b850)

#### **SideBodyCamera\Metadata.csv**
![Code_sbHVOq1jg1](https://github.com/AllenNeuralDynamics/Aind.Behavior.VrForaging/assets/159174908/085cbf11-0389-4a68-b67f-b284f6c68278)

**Comment by bruno-f-cruz** [comment]
Please match the timestamp axis. Your previous post zeros all timestamps whereas your last one doesn't. Thanks!

**Comment by NgD-Huy** [comment]
> Please match the timestamp axis. Your previous post zeros all timestamps whereas your last one doesn't. Additionally, try to include text instead of images. Copy-paste to code blocks limited by "```" works fine. Thanks!

Updated comment

**Comment by bruno-f-cruz** [comment]
As far as I can tell all data looks good.
First frame and last frame arrive in between the start and stop pwm. I will check the workflow but i suspect I am just sending two messages to stop the cameras (one when i stop the logging and a second one when bonsai closes all the hardware). This has no effects on the actual data so not that urgent to fix.

**Comment by NgD-Huy** [comment]
### **Register__StartCameras.bin**

<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>0</th>
      <th>MessageType</th>
    </tr>
    <tr>
      <th>Time</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>1809641.9474879999</th>
      <td>0</td>
      <td>READ</td>
    </tr>
    <tr>
      <th>1809641.9545600000</th>
      <td>1</td>
      <td>WRITE</td>
    </tr>
  </tbody>
</table>
</div>

### **Register__StopCameras.bin**
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>0</th>
      <th>MessageType</th>
    </tr>
    <tr>
      <th>Time</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>1809641.9495039999</th>
      <td>1</td>
      <td>READ</td>
    </tr>
    <tr>
      <th>1812810.4904960000</th>
      <td>1</td>
      <td>WRITE</td>
    </tr>
    <tr>
      <th>1812810.4938560000</th>
      <td>1</td>
      <td>EVENT</td>
    </tr>
  </tbody>
</table>
</div>

**Comment by bruno-f-cruz** [comment]
There appears to be an undocumented EVENT type message from this register. I am tracking the issue here: https://github.com/harp-tech/device.behavior/issues/18

Otherwise everything looks good with our workflow
