### ISSUE TITLE
Cannot make step size smaller than 1mm for lickspout movement

### ISSUE THREAD

**Issue by katrinanguyen7** [AllenNeuralDynamics/Aind.Behavior.VrForaging#292]
Cannot make step size smaller than 1mm in the GUI. When I enter any value under 1 (ie. 0.5), an error pops up saying 'Property value is not valid.'

**Comment by katrinanguyen7** [comment]
Bruno made an issue already

**Comment by bruno-f-cruz** [comment]
Closed via #289
