### ISSUE TITLE
Add calibration lookup table for treadmill brake

### ISSUE THREAD

**Issue by bruno-f-cruz** [AllenNeuralDynamics/Aind.Behavior.VrForaging#294]
This will likely require changing the current rig schema and adding a first citizen class to the aind behavior services
There are two options to keep this data:
- lookup table
- fitted function parameters

@Poofjunior can you give me an example of what data we should be keeping, along with domains of the data?

Once we decide this format, we also need to refactor the bonsai code to calibrate the online manipulation

**Comment by Poofjunior** [comment]
The calibration data I'm collecting is:
* input: current (12-bit but upscaled to 0 - 65535)
* output: measured torque (12-bit, not upscaled, with 2048 being the "zero torque" output.)

We want a table that stores:
* input: desired current
* output: actual current to produce desired current

**Comment by bruno-f-cruz** [comment]
Implemented in #289
