### ISSUE TITLE
Lick sensor LED is triggering during the session

### ISSUE THREAD

**Issue by tiffanyona** [AllenNeuralDynamics/Aind.Behavior.VrForaging#311]
We recently noticed that the LED was lighting up while the session is running. IT is possible something changed with the latest firmware update, it wasn't noticed before.

**Comment by bruno-f-cruz** [comment]
@Poofjunior Is the `OPLEDEN` flag implemented? Is it just a matter of sending the correct command via [R_OPERATION_CTRL](https://github.com/harp-tech/protocol/blob/main/Device.md#r_operation_ctrl-u16--operation-mode-configuration)?

**Comment by bruno-f-cruz** [comment]
Importantly, the  `VISUALEN` is the one that we need to set at start logging time

**Comment by bruno-f-cruz** [comment]
Fixed via b6065c0ab545bca4600e2aeb232b0348265b249a
